# Dependencies
markdown:         kramdown
highlighter:      rouge
gems: [jekyll-paginate, jekyll-gist, jekyll-github-metadata]

# Permalinks
permalink:        pretty

# Setup
title:            Kurt
tagline:          'A Programmer'
description:      'Technology blog about stuff I love!'
url:              http://www.kurtwang.com
baseurl:          /

author:
  name: Cong Wang
  url:  git@github.com:KurtWangRu/KurtWangRu.github.io.git
  email: cong.wang@rutgers.edu

paginate:         5

# Custom vars
version:          1.0

# Custom vars
github_link:	  https://github.com/KurtWangRu

# GitHub Metadata setup
repository: 	  KurtWangRu/KurtWangRu.github.io
# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 'kurtwang'
